# Generated by Django 5.0.9 on 2024-11-28 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_rename_comments_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="comment",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=300),
        ),
    ]
